#!/bin/bash
WIZARD_DATA_ACTION="$wizard_data_action"

echo "卸载时, 用户选择数据保留选项: $WIZARD_DATA_ACTION"

if [ "$WIZARD_DATA_ACTION" = "delete" ]; then
    echo "开始删除数据目录: $TRIM_PKGVAR 以及 $TRIM_DATA_SHARE_PATHS"
    rm -rf ${TRIM_PKGVAR}
    if [ -n "$TRIM_DATA_SHARE_PATHS" ]; then
        IFS=':' read -ra PATHS <<< "$TRIM_DATA_SHARE_PATHS"
        for p in "${PATHS[@]}"; do
            [ -n "$p" ] && rm -rf "$p"
        done
    fi
else
    echo "保留数据不动"
fi
exit 0